"""Harvest an AWS WAF token by letting the silent challenge run in a real browser.

AWS WAF's Challenge/CAPTCHA action ships a JS proof-of-work (token.js / challenge.js)
that runs invisibly on the protected page and, on success, sets the `aws-waf-token`
cookie. We navigate the real URL, let that JS execute, and poll the cookie jar — the
exact same shape as our cf_clearance solver (navigate → poll named cookie → return
jar+UA), just a different cookie name and no checkbox to click.

The token is bound to the client the same way cf_clearance is (IP + TLS/JA3 + UA), so
we pass the proxy through and return the replay warning.

ponytail: SILENT/JS challenge only — this has NO answer for AWS WAF's interactive
  visual CAPTCHA puzzle (the grid/carousel one). If a target ESCALATES to the puzzle,
  the cookie never sets and we time out. add visual-puzzle solve (drive the puzzle +
  Mistral vision, reuse recaptcha/image_solve.py) when a real target needs it.
"""
import asyncio
import logging
import time

import cloakbrowser

from solvers.common.browser import browser_kwargs, run_pre_actions, run_post_fetch

log = logging.getLogger(__name__)
_solve_lock = asyncio.Lock()

# CloudFront/WAF hard-blocks (datacenter IP, geo-block) serve an error page whose title
# matches one of these — the WAF JS never runs, so detect early and fail fast. Bare
# "error" is intentionally excluded (it substring-matched benign titles like "terror");
# the specific phrases still catch an "ERROR: ..." prefix via substring match.
_BLOCK_TITLES = ("403 forbidden", "access denied", "request blocked",
                 "the request could not be satisfied", "service unavailable",
                 "503", "error from cloudfront", "generated by cloudfront")


def _waf_token(cookies: list):
    """Return the aws-waf-token cookie record (whole dict) or None."""
    return next((c for c in cookies if c.get("name") == "aws-waf-token"), None)


def _title_is_block(title: str) -> bool:
    """Pure predicate: True if a page title matches a known CloudFront/WAF hard-block
    (case-insensitive substring against the specific block phrases)."""
    t = (title or "").lower()
    return any(b in t for b in _BLOCK_TITLES)


async def _is_cloudfront_block(page) -> bool:
    """True when the page is a CloudFront/WAF block error, not the real target."""
    try:
        title = await page.title()
    except Exception:
        return False
    return _title_is_block(title)


def _kwargs(proxy: str = None) -> dict:
    return browser_kwargs("TURNSTILE", proxy=proxy)


async def _navigate_and_poll(browser, url, timeout_s, pre_actions):
    """Navigate, run the silent WAF JS, poll for aws-waf-token.

    Returns (token, cookies, ua, lang, blocked, reason).
    reason is set on early fail (block / no_challenge / captcha_puzzle).
    """
    page = await browser.new_page()
    try:
        await page.goto(url, wait_until="domcontentloaded", timeout=45000)
        if pre_actions:
            await run_pre_actions(page, pre_actions)

        if await _is_cloudfront_block(page):
            ua = await page.evaluate("() => navigator.userAgent")
            return None, await page.context.cookies(), ua, "en-US", True, "cloudfront_block"

        # Visual CAPTCHA puzzle (interactive) — silent solver cannot finish this.
        try:
            html0 = (await page.content())[:8000].lower()
            if any(x in html0 for x in (
                "awswafcaptcha", "captcha.awswaf.com", "aws-waf-captcha",
                "goku-props", "gokuprops",
            )):
                # puzzle may still load async; wait briefly for cookie first
                pass
        except Exception:
            html0 = ""

        try:
            await page.mouse.move(120, 180)
            await page.mouse.wheel(0, 400)
            await page.evaluate("() => window.scrollTo(0, 200)")
        except Exception:
            pass

        tok, cookies = None, []
        deadline = time.monotonic() + max(15, timeout_s)
        reloaded = False
        saw_waf_js = False
        t_start = time.monotonic()
        while time.monotonic() < deadline:
            cookies = await page.context.cookies()
            tok = _waf_token(cookies)
            if not tok:
                try:
                    raw = await page.evaluate("() => document.cookie || ''")
                    for part in raw.split(";"):
                        part = part.strip()
                        if part.startswith("aws-waf-token="):
                            val = part.split("=", 1)[1]
                            if val:
                                tok = {"name": "aws-waf-token", "value": val, "domain": ""}
                                break
                except Exception:
                    pass
            if tok:
                break

            # Probe for silent challenge assets / visual captcha once in a while
            if not saw_waf_js and (time.monotonic() - t_start) > 3:
                try:
                    probe = await page.evaluate("""() => {
                      const html = (document.documentElement && document.documentElement.innerHTML) || '';
                      const h = html.slice(0, 200000).toLowerCase();
                      const scripts = [...document.scripts].map(s => (s.src||'')+s.textContent.slice(0,200)).join(' ').toLowerCase();
                      const blob = h + ' ' + scripts;
                      return {
                        silent: /token\\.js|challenge\\.js|awswaf|aws-waf|amazon-waf|gokuprops/.test(blob),
                        captcha: /awswafcaptcha|captcha\\.awswaf\\.com|aws-waf-captcha|visual captcha/.test(blob),
                      };
                    }""")
                    if probe.get("silent"):
                        saw_waf_js = True
                    if probe.get("captcha") and not tok:
                        # allow a few more seconds for silent path before declaring puzzle
                        if (time.monotonic() - t_start) > 12:
                            ua = await page.evaluate("() => navigator.userAgent")
                            return None, cookies, ua, "en-US", False, "captcha_puzzle"
                except Exception:
                    pass

            # Fail-fast: after ~18s no WAF markers and no token → not a silent-challenge page
            if (not saw_waf_js and not tok
                    and (time.monotonic() - t_start) > min(18, max(12, timeout_s // 3))):
                ua = await page.evaluate("() => navigator.userAgent")
                return None, cookies, ua, "en-US", False, "no_waf_challenge"

            if not reloaded and (time.monotonic() - t_start) > max(12, timeout_s // 3):
                reloaded = True
                try:
                    await page.reload(wait_until="domcontentloaded", timeout=30000)
                except Exception:
                    pass
            await asyncio.sleep(1)

        ua = await page.evaluate("() => navigator.userAgent")
        lang = await page.evaluate("() => navigator.language")
        reason = None if tok else ("timeout_no_token" if saw_waf_js else "no_waf_challenge")
        return tok, cookies, ua, lang, False, reason
    except Exception as e:
        log.warning("aws waf navigate/poll: %s", e)
        try:
            cookies = await page.context.cookies()
        except Exception:
            cookies = []
        try:
            ua = await page.evaluate("() => navigator.userAgent")
        except Exception:
            ua = "Mozilla/5.0"
        return None, cookies, ua, "en-US", False, f"nav_error:{str(e).splitlines()[0][:120]}"
    finally:
        await page.close()


async def solve_aws_waf(url: str, proxy: str = None, timeout_s: int = 60,
                        pre_actions: list = None, post_fetch: list = None) -> dict:
    """Navigate an AWS-WAF-protected URL, let the silent challenge set aws-waf-token,
    and return the token + everything needed to replay it from the same IP/UA.

    On a CloudFront/WAF hard-block (datacenter-IP 403), retries once through a fresh
    context (helps only if a proxy is set / rotates).
    """
    t0 = time.monotonic()
    async with _solve_lock:
        tok = cookies = ua = None
        lang = "en-US"
        reason = None
        for attempt in (1, 2):
            async with await cloakbrowser.launch_async(**_kwargs(proxy)) as browser:
                tok, cookies, ua, lang, blocked, reason = await _navigate_and_poll(
                    browser, url, timeout_s, pre_actions)
                if not blocked and (tok or reason not in (None, "cloudfront_block")):
                    break
                log.warning("AWS WAF: attempt %d blocked=%s reason=%s", attempt, blocked, reason)
                if attempt == 2:
                    tok = None

        result = {
            "token": tok["value"] if tok else "",
            "aws_waf_token": tok,
            "success": bool(tok),
            "cookies": cookies,
            "user_agent": ua,
            "headers": {"User-Agent": ua, "Accept-Language": lang},
            "proxy": proxy or None,
            "method": "silent-challenge",
            "elapsed": round(time.monotonic() - t0, 1),
            "warning": ("aws-waf-token is bound to IP + JA3/TLS + User-Agent. Replay "
                        "ONLY from the same proxy IP, with this exact User-Agent, over a "
                        "TLS stack producing the same JA3."),
        }
        if not tok:
            msgs = {
                "cloudfront_block": (
                    "CloudFront/WAF hard-block (403) — need residential proxy or different URL"),
                "captcha_puzzle": (
                    "AWS WAF interactive visual CAPTCHA (not supported; silent challenge only)"),
                "no_waf_challenge": (
                    "page has no silent AWS WAF challenge (no token.js/challenge.js) — "
                    "not a valid silent-WAF target; pass a real WAF-protected URL + proxy"),
                "timeout_no_token": (
                    "silent challenge ran but aws-waf-token never set "
                    "(escalate to puzzle or IP blocked) — try residential proxy"),
            }
            result["error"] = msgs.get(
                reason or "",
                reason or ("aws-waf-token not set — CloudFront block or visual puzzle "
                           "(silent-only). Pass residential proxy + real WAF URL."),
            )
            if reason:
                result["reason"] = reason
        if post_fetch and tok:
            async with await cloakbrowser.launch_async(**_kwargs(proxy)) as browser:
                page = await browser.new_page()
                try:
                    await page.goto(url, wait_until="domcontentloaded", timeout=45000)
                    result["post_fetch"] = await run_post_fetch(page, post_fetch, tok["value"])
                finally:
                    await page.close()
        return result

# skipped: interactive AWS WAF visual-puzzle solve — silent challenge covers the common
#   case; add puzzle-drive + Mistral vision (reuse recaptcha/image_solve.py) when a
#   target escalates. skipped: sec-ch-ua header capture — UA + Accept-Language + jar
#   cover the documented binding; add if a target rejects replay despite matching IP+UA+JA3.
